Repository SSA-FE/formssafe-fe, pull requests merged in 2024-04, with the labels that each got.

#33 Feat/#32 login 작업 마무리
  src/App.tsx
  src/assets/gif/spinner.gif
  src/components/Loading.tsx
  src/components/auth/CheckUserAuth.tsx
  src/components/auth/GoogleOAuth.tsx
  src/config.ts
  src/main.tsx
  src/router/index.tsx
Labels: feat

#38 Chore/#37 RTK Query로 서버사이드 데이터 관리하기
  src/api/userApi.ts
  src/components/Topbar.tsx
  src/components/Workspace/tab.tsx
  src/components/auth/GoogleOAuth.tsx
  src/components/auth/LoginRedirect.tsx
  src/components/users/userSlice.tsx
  src/hooks/.gitkeep
  src/hooks/useFetchUsers.tsx
  src/interface/.gitkeep
  src/interface/redux.tsx
  src/pages/Myspace.tsx
  src/store/auth.tsx
  src/store/index.tsx
Labels: chore

#43 Feat/#31 form question block list
  .eslintrc.cjs
  src/assets/icons/option-prefix-checkbox.svg
  src/assets/icons/option-prefix-dropdown.svg
  src/assets/icons/option-prefix-single.svg
  src/assets/icons/text-icon.svg
  src/components/Myspace/FormMain.tsx
  src/components/Myspace/questionBlock/OptionList.tsx
  src/components/Myspace/questionBlock/QuestionBlock.tsx
  src/components/Myspace/questionBlockForm/QuestionBlockForm.tsx
  src/components/Myspace/questionBlockForm/questionBlockFormSlice.ts
  src/components/Myspace/questionBlockList/QuestionBlockList.tsx
  src/components/Myspace/questionBlockList/questionBlockListSlice.ts
  src/store/index.tsx
Labels: feat

#51 feat: 질문블럭리스트 dnd적용
  package-lock.json
  package.json
  src/components/Myspace/questionBlock/QuestionBlock.tsx
  src/components/Myspace/questionBlockList/QuestionBlockList.tsx
  src/components/Myspace/questionBlockList/questionBlockListSlice.ts
Labels: feat

#48 Feat/#46 마이스페이스 페이지 - 내가 작성한 설문 리스트 표시
  src/api/activityApi.ts
  src/components/Myspace/SortDropdown.tsx
  src/components/Myspace/SurveyCard.tsx
  src/config.ts
  src/pages/Myspace.tsx
  src/store/index.tsx
Labels: feat

#56 Design/#49 마이스페이스 디자인 및 api 연결 작업
  src/api/activityApi.ts
  src/components/Myspace/FormToolBar.tsx
  src/components/Myspace/MyspaceMain.tsx
  src/components/Myspace/MyspacePanel.tsx
  src/components/Myspace/SearchBar.tsx
  src/components/Myspace/SortDropdown.tsx
  src/components/Myspace/SurveyCard.tsx
  src/components/Myspace/toolbar/Toolbar.tsx
  src/components/Myspace/toolbar/toolbarInputSlice.ts
  src/index.css
  src/pages/Myspace.tsx
  src/store/index.tsx
Labels: feat, design

#62 Feat/#57 Topbar 알람, 프로필 모달 작업
  package.json
  public/.gitkeep
  public/svg/active-alarm-icon.svg
  public/svg/edit-icon.svg
  public/svg/inactive-alarm-icon.svg
  public/svg/logout-icon.svg
  src/api/userApi.ts
  src/assets/icons/ActiveAlarmIcon.tsx
  src/assets/icons/EditIcon.tsx
  src/assets/icons/InactiveAlarmIcon.tsx
  src/assets/icons/LogoutIcon.tsx
  src/assets/icons/alarm-icon.svg
  src/assets/icons/index.ts
  src/components/Topbar.tsx
  src/components/auth/LoginRedirect.tsx
  src/pages/Myspace.tsx
  vite.config.ts
Labels: feat, design

#65 Design/#64 board panel 디자인 작업
  package-lock.json
  public/svg/search-icon.svg
  src/assets/icons/SearchIcon.tsx
  src/assets/icons/index.ts
  src/components/Board/BoardMain.tsx
  src/components/Board/panel/BoardPanel.tsx
  src/components/Board/panel/SearchForm.tsx
  src/components/Board/panel/SortButton.tsx
  src/components/Myspace/SearchBar.tsx
  src/components/Topbar.tsx
  src/components/auth/LoginRedirect.tsx
  src/pages/Board.tsx
  src/pages/Workspace.tsx
  src/router/index.tsx
Labels: design

#69 Design/#66 Board 페이지 및 설문카드 디자인 변경
  public/svg/category-list-icon.svg
  public/svg/main-logo-icon.svg
  public/svg/status-icon.svg
  src/api/viewApi.ts
  src/assets/icons/CategoryListIcon.tsx
  src/assets/icons/MainLogoIcon.tsx
  src/assets/icons/StatusIcon.tsx
  src/assets/icons/index.ts
  src/assets/images/dafaultImg.jpg
  src/components/Board/BoardMain.tsx
  src/components/Board/main/BoardMain.tsx
  src/components/Board/main/BoardToolbar.tsx
  src/components/Board/main/CategoryDropdown.tsx
  src/components/Board/main/StatusDropdown.tsx
  src/components/Board/panel/BoardPanel.tsx
  src/components/Board/panel/SearchForm.tsx
  src/components/Board/panel/SortButton.tsx
  src/components/Myspace/MyspaceMain.tsx
  src/components/Myspace/SurveyCard.tsx
  src/components/Topbar.tsx
  src/pages/Board.tsx
  src/store/index.tsx
  tailwind.config.js
Labels: feat, design

#78 Fix/#73 topbar button issue
  src/components/Board/main/CategoryDropdown.tsx
  src/components/Board/main/StatusDropdown.tsx
  src/components/Topbar.tsx
Labels: bug

#82 fix: 폰트 적용 이슈 해결
  index.html
  src/index.css
Labels: bug, fix
