Repository SSA-FE/formssafe-fe, pull requests merged in 2024-05, with the labels that each got.

#85 refactor: topbar 컴포넌트 모달 분리 및 최적화 작업
  index.html
  src/api/userApi.ts
  src/components/Layout.tsx
  src/components/Myspace/FormCard.tsx
  src/components/Topbar.tsx
  src/components/topbar/AlarmModal.tsx
  src/components/topbar/ProfileModal.tsx
  src/components/topbar/Topbar.tsx
Labels: refactoring

#87 Chore/#71 boardViewSlice 세팅 및 적용
  src/api/viewApi.ts
  src/components/Board/boardViewSlice.ts
  src/components/Board/main/BoardToolbar.tsx
  src/components/Board/main/CategoryDropdown.tsx
  src/components/Board/main/StatusDropdown.tsx
  src/components/Board/panel/SearchForm.tsx
  src/components/Myspace/FormMain.tsx
  src/components/Myspace/MyspacePanel.tsx
  src/components/Myspace/SearchBar.tsx
  src/components/Myspace/SortDropdown.tsx
  src/components/Myspace/questionBlock/QuestionBlock.tsx
  src/components/Myspace/questionBlockList/QuestionBlockList.tsx
  src/hooks/.gitkeep
  src/hooks/useAppDispatch.ts
  src/store/index.tsx
Labels: chore

#88 Feat/#76 question response page layout
  src/assets/icons/reward-icon.svg
  src/components/Form/FormBody.tsx
  src/components/Form/FormHeader.tsx
  src/pages/Form.tsx
  src/router/index.tsx
  src/utils/calculateLeftDays.ts
Labels: design

#90 Feat/#59 editor option bar
  package-lock.json
  src/assets/icons/optionsIcons.tsx
  src/components/Myspace/FormInfoBar.tsx
  src/components/Myspace/FormMain.tsx
  src/components/Myspace/FormOptionBar.tsx
  src/components/Myspace/OptionsToggle.tsx
  src/components/Myspace/QuestionOptions.tsx
  src/components/Myspace/questionBlock/OptionList.tsx
  src/components/Myspace/questionBlock/QuestionBlock.tsx
  src/components/Myspace/questionBlock/questionBlockSlice.ts
  src/components/Myspace/questionBlockList/questionBlockListSlice.ts
  src/index.css
  src/pages/Editor.tsx
  src/pages/Home.tsx
  src/types/questionTypes.ts
  vite.config.ts
Labels: feat

#94 Design/#83 myspace layout
  public/svg/dropdown-icon.svg
  public/svg/edit-icon.svg
  src/assets/icons/DropdownIcon.tsx
  src/assets/icons/EditIcon.tsx
  src/assets/icons/index.ts
  src/components/Myspace/FormCard.tsx
  src/components/Myspace/MyspaceMain.tsx
  src/components/Myspace/MyspacePanel.tsx
  src/components/Myspace/MyspaceSidebar.tsx
  src/components/Myspace/SearchBar.tsx
  src/components/Myspace/SortDropdown.tsx
  src/components/Myspace/toolbar/MyspaceToolbar.tsx
  src/components/Myspace/toolbar/Toolbar.tsx
  src/components/topbar/ProfileModal.tsx
  src/components/topbar/Topbar.tsx
  src/components/topbar/topbarSlice.ts
  src/pages/Home.tsx
  src/pages/Myspace.tsx
  src/store/index.tsx
Labels: feat, design

#96 Feat/#91 topbar navigation
  src/assets/icons/EditIcon.tsx
  src/assets/icons/MainLogoIcon.tsx
  src/components/Myspace/MyspacePanel.tsx
  src/components/topbar/Topbar.tsx
Labels: feat

#97 FEAT/#84 nickname 관련 에러 핸들링
  src/components/auth/LoginRedirect.tsx
  src/components/topbar/ProfileModal.tsx
  tailwind.config.js
Labels: feat

#100 Design/#93 Home, Footer Layout 디자인 작업
  public/svg/footerLogo-icon.svg
  public/svg/form-example-icon1.svg
  public/svg/form-example-icon2.svg
  src/assets/icons/FooterLogoIcon.tsx
  src/assets/icons/FormExampleIcon1.tsx
  src/assets/icons/FormExampleIcon2.tsx
  src/assets/icons/index.ts
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Loading.tsx
  src/index.css
  src/pages/Board.tsx
  src/pages/Home.tsx
  tailwind.config.js
Labels: feat, design

#103 Feat/#61 stat block
  package-lock.json
  package.json
  src/api/formApi.ts
  src/assets/icons/SingleIcon.tsx
  src/assets/icons/arrow-bottom.svg
  src/assets/icons/arrow-up.svg
  src/assets/icons/edit-square-icon.svg
  src/assets/icons/index.ts
  src/assets/icons/option-icon.svg
  src/assets/icons/print-icon.svg
  src/assets/icons/setting-icon.svg
  src/assets/icons/user-icon.svg
  src/components/Statistic/PersonalResult.tsx
  src/components/Statistic/StatResult.tsx
  src/components/Statistic/StatTopBar.tsx
  src/components/Statistic/itemBlock/Chart.tsx
  src/components/Statistic/itemBlock/EssayQuestionBlock.tsx
  src/components/Statistic/itemBlock/Item.tsx
  src/components/Statistic/itemBlock/MutipleChoiceBlock.tsx
  src/components/Statistic/remoteForm/Question.tsx
  src/components/Statistic/remoteForm/RemoteForm.tsx
  src/components/Statistic/userResultForm/User.tsx
  src/components/Statistic/userResultForm/UserResultForm.tsx
  src/config.ts
  src/pages/Stat.tsx
  src/pages/StatDetail.tsx
  src/router/index.tsx
  src/store/index.tsx
Labels: feat

#104 Feat/#86 alarm notification api
  src/api/notificationApi.ts
  src/components/Myspace/FormCard.tsx
  src/components/topbar/AlarmModal.tsx
  src/components/topbar/ProfileModal.tsx
  src/components/topbar/Topbar.tsx
  src/config.ts
  src/index.css
  src/store/index.tsx
Labels: feat

#108 Fix/#107 stat issue
  src/assets/icons/AnswertOptionsIcons.tsx
  src/components/Statistic/PersonalResult.tsx
  src/components/Statistic/StatResult.tsx
  src/components/Statistic/StatTopBar.tsx
  src/components/Statistic/itemBlock/Chart.tsx
  src/components/Statistic/itemBlock/EssayQuestionBlock.tsx
  src/components/Statistic/itemBlock/Item.tsx
  src/components/Statistic/itemBlock/MutipleChoiceBlock.tsx
  src/components/Statistic/remoteForm/RemoteForm.tsx
  src/components/Statistic/userResultForm/UserResultForm.tsx
  src/pages/Stat.tsx
  src/pages/StatDetail.tsx
Labels: bug, fix

#109 Feat/#92 formcard UI 동적 렌더링 및 기타 작업
  public/svg/list-icon.svg
  src/api/activityApi.ts
  src/assets/icons/ListIcon.tsx
  src/assets/icons/index.ts
  src/assets/images/dafaultImg.jpg
  src/assets/images/defaultImg.png
  src/components/Board/boardViewSlice.ts
  src/components/Board/main/BoardMain.tsx
  src/components/Board/main/BoardToolbar.tsx
  src/components/Board/main/StatusDropdown.tsx
  src/components/Board/panel/SearchForm.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Myspace/FormCard.tsx
  src/components/Myspace/MyspaceMain.tsx
  src/components/Myspace/MyspacePanel.tsx
  src/components/Myspace/MyspaceSidebar.tsx
  src/components/Myspace/SortDropdown.tsx
  src/components/Myspace/toolbar/toolbarInputSlice.ts
  src/components/topbar/Topbar.tsx
  src/pages/Board.tsx
  src/pages/Form.tsx
  src/pages/Home.tsx
  src/pages/Myspace.tsx
  src/utils/tagPalette.ts
Labels: feat

#112 Feat/#111 popular form carousel
  package-lock.json
  package.json
  public/svg/hot-icon.svg
  src/api/viewApi.ts
  src/assets/icons/HotIcon.tsx
  src/assets/icons/index.ts
  src/components/Board/carousel/BoardCarousel.tsx
  src/components/Board/main/BoardMain.tsx
  src/index.css
  src/pages/Board.tsx
Labels: feat
